kind: pipeline
name: default

steps:
- name: pytest-step
  image: python
  commands:
  - pip install -r requirements.txt
  - pytest
  - python app.py

- name: mysql-step
  image: mysql
  commands:
  - sleep 15
  - mysql -u root -h database --execute="SELECT VERSION();"

services:
- name: database
  image: mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test