name: Action2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: pip install
        run: pip install -r requirements.txt
      - name: pytest
        run: pytest
      - name: python
        run: python app.py
        